version: "3"

services:
  flask:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - .:/code
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=production
    restart: always
    networks:
      - default

  nginx:
    image: nginx:stable
    ports:
      - 8005:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - flask
    networks:
      - default
      - nginx-proxy_nginx-proxy
    restart: always
    environment:
      - VIRTUAL_PORT=8005
      - VIRTUAL_HOST=bookshelf.shirleyyin.com
      - LETSENCRYPT_HOST=bookshelf.shirleyyin.com
      - LETSENCRYPT_EMAIL=contact@shirleyyin.com

networks:
  default:
    driver: bridge
  nginx-proxy_nginx-proxy:
    external: true